"""add country handle

Revision ID: 01f9c4d67444
Revises: d8a35ad06869
Create Date: 2017-05-19 05:18:01.349188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f9c4d67444'
down_revision = 'd8a35ad06869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('fb_access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'state')
    op.drop_column('users', 'fb_access_token')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###
