"""add last matched

Revision ID: 0cc5dea432ad
Revises: 7a2a4a7ba9b3
Create Date: 2017-04-15 09:31:03.414672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc5dea432ad'
down_revision = '7a2a4a7ba9b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_matched_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_matched_date')
    # ### end Alembic commands ###
