"""create table

Revision ID: 2971993e5399
Revises: 
Create Date: 2017-04-14 10:23:36.552401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2971993e5399'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matching_queue',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_languages',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('language_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], [u'languages.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'language_id')
    )
    op.create_table('user_partners',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('partner_id', sa.String(), nullable=False),
    sa.CheckConstraint(u'user_id <> partner_id'),
    sa.ForeignKeyConstraint(['partner_id', 'user_id'], [u'user_partners.user_id', u'user_partners.partner_id'], ondelete=u'CASCADE', initially=u'DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['partner_id'], [u'users.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'partner_id'),
    sa.UniqueConstraint('partner_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_partners')
    op.drop_table('user_languages')
    op.drop_table('matching_queue')
    op.drop_table('users')
    op.drop_table('languages')
    # ### end Alembic commands ###
