"""notification

Revision ID: 31e965553288
Revises: b2103f9f9be6
Create Date: 2017-05-29 12:32:34.791097

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '31e965553288'
down_revision = 'b2103f9f9be6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
                    sa.Column('id', sa.Integer(), nullable=False,
                              autoincrement=True),
                    sa.Column('target_user', sa.String(), index=True,
                              nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('created_at', sa.Date(), nullable=True),
                    sa.Column('success', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
