"""add fb_id

Revision ID: 399a02b8d8e3
Revises: 448dcfcd145a
Create Date: 2017-04-05 04:15:38.120126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '399a02b8d8e3'
down_revision = '448dcfcd145a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fb_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fb_id')
    # ### end Alembic commands ###
