"""add_locale

Revision ID: 43392708fe4f
Revises: 31e965553288
Create Date: 2017-05-29 13:19:57.908784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43392708fe4f'
down_revision = '31e965553288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('locale', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locale')
    # ### end Alembic commands ###
