"""add location settings

Revision ID: 448dcfcd145a
Revises: fc5153cee388
Create Date: 2017-04-02 10:51:24.237832

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '448dcfcd145a'
down_revision = 'fc5153cee388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users',
                  sa.Column('current_latitude', sa.Float(), nullable=True))
    op.add_column('users',
                  sa.Column('current_longitude', sa.Float(), nullable=True))
    op.add_column('users',
                  sa.Column('location_enabled', sa.Boolean(), default=False,
                            nullable=True))
    op.add_column('users',
                  sa.Column('search_radius', sa.Integer(), default=400,
                            nullable=True))
    op.add_column('users', sa.Column('last_matched', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'search_radius')
    op.drop_column('users', 'location_enabled')
    op.drop_column('users', 'current_latitude')
    op.drop_column('users', 'current_longitude')
    op.drop_column('users', 'last_matched')
    # ### end Alembic commands ###
