"""add gender

Revision ID: fc5153cee388
Revises: 6333e7fa7bd1
Create Date: 2017-03-24 07:57:04.780230

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fc5153cee388'
down_revision = '2971993e5399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users',
                  sa.Column('finding_genders', sa.String(), default="male,female",
                            nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('users', 'finding_genders')
    # ### end Alembic commands ###
